import type { VaAircraft, VaAirport, VaFleet, VaRank } from "./types";

/**
 * vOCN reference data for the SAMPLE source.
 *
 * What is real and what is not, because the difference matters in a client demo:
 *  - REAL, from virtualocn.de (public, and vOCN asked us to use it): the two
 *    bases, the twenty destinations, the three Airbus types and their counts
 *    (A320-200 x18, A330-200 x2, A330-300 x13).
 *  - INVENTED: every registration, every pilot, the rank thresholds. vOCN does
 *    not publish ranks; the ladder follows vAMSYS's documented example shape.
 *  - Pilot names are deliberately synthetic. Real vOCN members' names beside
 *    invented hours and landing rates would be a fabricated record about
 *    identifiable people — the same rule the FastFox preview follows.
 */

export const VOCN_AIRPORTS: VaAirport[] = [
  {
    icao: "EDDF",
    iata: "FRA",
    name: "Frankfurt am Main",
    city: "Frankfurt",
    country: "DE",
    lat: 50.0379,
    lon: 8.5622,
    region: "HUB",
  },
  {
    icao: "EDDM",
    iata: "MUC",
    name: "Munich Franz Josef Strauss",
    city: "Munich",
    country: "DE",
    lat: 48.3538,
    lon: 11.7861,
    region: "HUB",
  },
  // Mediterranean
  {
    icao: "LEPA",
    iata: "PMI",
    name: "Palma de Mallorca",
    city: "Palma",
    country: "ES",
    lat: 39.5517,
    lon: 2.7388,
    region: "MED",
  },
  {
    icao: "LGIR",
    iata: "HER",
    name: "Heraklion Nikos Kazantzakis",
    city: "Heraklion",
    country: "GR",
    lat: 35.3397,
    lon: 25.1803,
    region: "MED",
  },
  {
    icao: "LGRP",
    iata: "RHO",
    name: "Rhodes Diagoras",
    city: "Rhodes",
    country: "GR",
    lat: 36.4054,
    lon: 28.0862,
    region: "MED",
  },
  {
    icao: "LDSP",
    iata: "SPU",
    name: "Split",
    city: "Split",
    country: "HR",
    lat: 43.5389,
    lon: 16.298,
    region: "MED",
  },
  {
    icao: "LEIB",
    iata: "IBZ",
    name: "Ibiza",
    city: "Ibiza",
    country: "ES",
    lat: 38.8729,
    lon: 1.3731,
    region: "MED",
  },
  // Atlantic islands
  {
    icao: "GCTS",
    iata: "TFS",
    name: "Tenerife South",
    city: "Tenerife",
    country: "ES",
    lat: 28.0445,
    lon: -16.5725,
    region: "ATLANTIC",
  },
  {
    icao: "GCLP",
    iata: "LPA",
    name: "Gran Canaria",
    city: "Las Palmas",
    country: "ES",
    lat: 27.9319,
    lon: -15.3866,
    region: "ATLANTIC",
  },
  {
    icao: "GCFV",
    iata: "FUE",
    name: "Fuerteventura",
    city: "Fuerteventura",
    country: "ES",
    lat: 28.4527,
    lon: -13.8638,
    region: "ATLANTIC",
  },
  {
    icao: "GCRR",
    iata: "ACE",
    name: "Lanzarote César Manrique",
    city: "Lanzarote",
    country: "ES",
    lat: 28.9455,
    lon: -13.6052,
    region: "ATLANTIC",
  },
  {
    icao: "LPMA",
    iata: "FNC",
    name: "Madeira Cristiano Ronaldo",
    city: "Funchal",
    country: "PT",
    lat: 32.6979,
    lon: -16.7745,
    region: "ATLANTIC",
  },
  // North America
  {
    icao: "CYYZ",
    iata: "YYZ",
    name: "Toronto Pearson",
    city: "Toronto",
    country: "CA",
    lat: 43.6777,
    lon: -79.6248,
    region: "NORTH_AMERICA",
  },
  {
    icao: "CYHZ",
    iata: "YHZ",
    name: "Halifax Stanfield",
    city: "Halifax",
    country: "CA",
    lat: 44.8808,
    lon: -63.5086,
    region: "NORTH_AMERICA",
  },
  {
    icao: "PANC",
    iata: "ANC",
    name: "Anchorage Ted Stevens",
    city: "Anchorage",
    country: "US",
    lat: 61.1743,
    lon: -149.9963,
    region: "NORTH_AMERICA",
  },
  {
    icao: "KLAS",
    iata: "LAS",
    name: "Las Vegas Harry Reid",
    city: "Las Vegas",
    country: "US",
    lat: 36.084,
    lon: -115.1537,
    region: "NORTH_AMERICA",
  },
  {
    icao: "KMCO",
    iata: "MCO",
    name: "Orlando",
    city: "Orlando",
    country: "US",
    lat: 28.4312,
    lon: -81.3081,
    region: "NORTH_AMERICA",
  },
  // Africa & Indian Ocean
  {
    icao: "HTZA",
    iata: "ZNZ",
    name: "Zanzibar Abeid Amani Karume",
    city: "Zanzibar",
    country: "TZ",
    lat: -6.222,
    lon: 39.2249,
    region: "AFRICA_INDIAN_OCEAN",
  },
  {
    icao: "HKMO",
    iata: "MBA",
    name: "Mombasa Moi",
    city: "Mombasa",
    country: "KE",
    lat: -4.0348,
    lon: 39.5942,
    region: "AFRICA_INDIAN_OCEAN",
  },
  {
    icao: "FIMP",
    iata: "MRU",
    name: "Mauritius Sir Seewoosagur Ramgoolam",
    city: "Mauritius",
    country: "MU",
    lat: -20.4302,
    lon: 57.6836,
    region: "AFRICA_INDIAN_OCEAN",
  },
  {
    icao: "FYWH",
    iata: "WDH",
    name: "Windhoek Hosea Kutako",
    city: "Windhoek",
    country: "NA",
    lat: -22.4799,
    lon: 17.4709,
    region: "AFRICA_INDIAN_OCEAN",
  },
  {
    icao: "FACT",
    iata: "CPT",
    name: "Cape Town",
    city: "Cape Town",
    country: "ZA",
    lat: -33.9715,
    lon: 18.6021,
    region: "AFRICA_INDIAN_OCEAN",
  },
];

/** Registrations are invented (D- prefix, German register style). Counts are vOCN's. */
function regs(prefix: string, letters: string, fleet: VaFleet): VaAircraft[] {
  return letters.split("").map((c) => ({ reg: `${prefix}${c}`, fleet }));
}
export const VOCN_FLEET: VaAircraft[] = [
  ...regs("D-AOC", "ABCDEFGHIJKLMNOPQR", "A320-200"), // 18
  ...regs("D-AOX", "AB", "A330-200"), // 2
  ...regs("D-AOK", "ABCDEFGHIJKLM", "A330-300"), // 13
];

/**
 * Rank ladder. Shape from vAMSYS's docs (name, abbreviation, hour / point /
 * PIREP thresholds, all of which must be met; honorary ranks awarded by hand).
 * vOCN's real ladder is not public, so these thresholds are ours.
 */
export const VOCN_RANKS: VaRank[] = [
  { key: "cdt", name: "Cadet", abbr: "CDT", hours: 0, points: 0, pireps: 0, stripes: 1 },
  {
    key: "so",
    name: "Second Officer",
    abbr: "S/O",
    hours: 15,
    points: 1500,
    pireps: 8,
    stripes: 2,
  },
  {
    key: "fo",
    name: "First Officer",
    abbr: "F/O",
    hours: 60,
    points: 6000,
    pireps: 30,
    stripes: 3,
  },
  {
    key: "sfo",
    name: "Senior First Officer",
    abbr: "SFO",
    hours: 150,
    points: 15000,
    pireps: 70,
    stripes: 3,
  },
  { key: "cpt", name: "Captain", abbr: "CPT", hours: 300, points: 30000, pireps: 130, stripes: 4 },
  {
    key: "scp",
    name: "Senior Captain",
    abbr: "SCP",
    hours: 600,
    points: 60000,
    pireps: 250,
    stripes: 4,
  },
  // Honorary (vAMSYS: one allowed beside the regular rank)
  {
    key: "ltc",
    name: "Line Training Captain",
    abbr: "LTC",
    hours: 0,
    points: 0,
    pireps: 0,
    stripes: 4,
    honorary: true,
  },
  {
    key: "ops",
    name: "Operations Staff",
    abbr: "OPS",
    hours: 0,
    points: 0,
    pireps: 0,
    stripes: 4,
    honorary: true,
  },
];

export const FIRST_NAMES = [
  "Lukas",
  "Lena",
  "Jonas",
  "Mia",
  "Felix",
  "Hannah",
  "Paul",
  "Lea",
  "Maximilian",
  "Anna",
  "Tim",
  "Sophie",
  "Niklas",
  "Laura",
  "Jan",
  "Clara",
  "Moritz",
  "Emma",
  "Tobias",
  "Johanna",
  "Florian",
  "Katharina",
  "Sebastian",
  "Marie",
  "Dominik",
  "Julia",
  "Matteo",
  "Elena",
  "Pieter",
  "Sanne",
  "Oskar",
  "Freya",
  "Aleksander",
  "Zofia",
  "Luca",
  "Chiara",
  "Mateus",
  "Inês",
  "Arvid",
  "Liv",
  "Rafael",
  "Nora",
  "Emil",
  "Ida",
  "Kaan",
  "Selin",
  "Daniel",
  "Sarah",
  "Benedikt",
  "Theresa",
];
export const LAST_NAMES = [
  "Brandt",
  "Vogel",
  "Kessler",
  "Hartwig",
  "Lindner",
  "Adler",
  "Sommer",
  "Falk",
  "Reuter",
  "Winkler",
  "Albrecht",
  "Engel",
  "Kraus",
  "Lorenz",
  "Seidel",
  "Pohl",
  "Brenner",
  "Haas",
  "Roth",
  "Kuhn",
  "Stein",
  "Moser",
  "Busch",
  "Graf",
  "Dietrich",
  "Ostermann",
  "de Vries",
  "Jansen",
  "Nowak",
  "Kowalski",
  "Rossi",
  "Ferreira",
  "Lindqvist",
  "Hansen",
  "Novák",
  "Yilmaz",
  "Weiss",
  "Horn",
  "Berger",
  "Frank",
  "Scholz",
  "Pfeiffer",
  "Kaiser",
  "Wagner",
  "Baumann",
  "Ludwig",
  "Keller",
];
export const PILOT_COUNTRIES = [
  "DE",
  "DE",
  "DE",
  "DE",
  "DE",
  "DE",
  "DE",
  "AT",
  "CH",
  "NL",
  "PL",
  "IT",
  "PT",
  "SE",
  "DK",
  "CZ",
  "TR",
  "GB",
  "CA",
  "US",
];
export const SIMULATORS = [
  "MSFS 2024",
  "MSFS 2024",
  "MSFS 2020",
  "X-Plane 12",
  "X-Plane 12",
  "Prepar3D v5",
];
